spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/predicta}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

scrape.source-urls=${SCRAPE_SOURCE_URLS:https://traffic.tag-ip.com/index.html#map=13/5290085.13/-2148941.17/0,https://traffic.tag-ip.com/index.html#map=13/5289339.87/-2134112.38/0}
scrape.tile-template=${SCRAPE_TILE_TEMPLATE:https://traffic.tag-ip.com/tiles/{zoom}/{x}/{y}.pbf}